// ============================================================
// HEME-ONC CLINICAL REFERENCE — DATA FILE
// ============================================================
// To add a new condition: copy any existing block, change the
// id/label/specialty/content, and save. No HTML changes needed.
//
// history and exam each have two modes:
//   quick: short negative-framed bullets for at-a-glance use
//   full:  comprehensive positive-framed list with reasoning
// labs.copyable: array of strings joined as comma-separated line
// labs.other: imaging and other investigations (read-only list)
// specialty: "hematology" or "oncology"
// ============================================================

var conditions = [

  // ─────────────────────────────────────────────
  // HEMATOLOGY
  // ─────────────────────────────────────────────

  {
    id: "lymphadenopathy",
    label: "Lymphadenopathy",
    specialty: "hematology",
    history: {
      quick: [
        "No fevers, drenching night sweats, or weight loss (>10% over 6 months)",
        "No pruritus or alcohol-induced nodal pain",
        "No recent infection, sick contacts, tick exposure, travel, STI risk, or known HIV",
        "No prior malignancy or family history of lymphoma",
        "No medications associated with pseudolymphoma (phenytoin, carbamazepine, allopurinol)",
        "No symptoms of autoimmune disease (rash, joint pain, dry eyes/mouth)",
      ],
      full: [
        "Duration and rate of growth — acute (<2 wks) vs subacute vs chronic",
        "Constitutional symptoms: fevers, drenching night sweats, weight loss (>10% in 6 months)",
        "Pruritus (generalized, without rash)",
        "Alcohol-induced nodal pain (classic but uncommon — Hodgkin lymphoma)",
        "Pain or tenderness in nodes",
        "Travel history, animal exposures, tick exposure, sick contacts",
        "Sexual history / STI risk (syphilis, HIV, HSV)",
        "Prior malignancy or personal/family history of lymphoma",
        "Medications: phenytoin, carbamazepine, allopurinol, hydralazine",
        "Occupation and environmental exposures",
        "Systemic symptoms suggesting autoimmune disease: rash, joint pain, dry eyes/mouth",
      ],
    },
    exam: {
      quick: [
        "Node size, consistency (rubbery vs hard/matted), mobility, tenderness — document location(s)",
        "Localized vs generalized distribution",
        "No splenomegaly or hepatomegaly",
        "No skin rash, jaundice, or petechiae",
        "No tonsillar enlargement, pharyngitis, or oral lesions",
        "No signs of SVC obstruction",
      ],
      full: [
        "Node characteristics: size (>1 cm is abnormal in most regions), consistency, mobility, tenderness",
        "Distribution: localized (one region) vs generalized (≥2 non-contiguous regions)",
        "Cervical, supraclavicular, axillary, epitrochlear, inguinal, femoral, popliteal chains",
        "Supraclavicular adenopathy: right → lung/mediastinum; left (Virchow's) → abdominal malignancy",
        "Splenomegaly (percuss and palpate) — if present, strongly favors systemic process",
        "Hepatomegaly",
        "Skin: rash, petechiae, lesions, jaundice",
        "ENT: pharyngitis, tonsillar enlargement/exudate, oral lesions",
        "Chest: pleural effusion, SVC syndrome signs",
      ],
    },
    considerations: [
      "Broad DDx: reactive (infection, autoimmune, drug), primary lymphoid malignancy, metastatic solid tumor, granulomatous disease (sarcoid, TB)",
      "Age-adjusted DDx: infectious mononucleosis/EBV in young adults; lymphoma, CLL, metastatic cancer in older adults",
      "High-risk features: supraclavicular location, size >2 cm, firm/hard/fixed, non-tender, progressive growth, B symptoms, age >40",
      "Low-risk features: tender, soft/rubbery, <1 cm, localized to head/neck with clear infectious source",
      "Threshold for biopsy: >1 cm, firm, non-tender, no clear benign explanation, persisting >4–6 weeks — excisional preferred over core for architecture",
      "Do NOT start steroids before biopsy if lymphoma is on the differential",
      "PET-CT preferred over CT alone if lymphoma strongly suspected",
      "If EBV confirmed in young patient with monospot, observation reasonable for 4–6 weeks before biopsy",
      "Flow cytometry on peripheral blood if lymphocytosis >5×10⁹/L or atypical lymphocytes on film",
    ],
    labs: {
      copyable: ["CBC","peripheral blood film","creatinine","ALT","ALK phos","bili","LDH","uric acid","ESR","CRP","ferritin","albumin","EBV VCA IgM/IgG","CMV IgM/IgG","HIV 4th gen Ag/Ab","HBsAg","HBcAb","HCV Ab","SPEP","beta-2 microglobulin"],
      other: [
        "CT neck/chest/abdomen/pelvis with IV contrast",
        "PET-CT if lymphoma suspected (preferred staging modality)",
        "Excisional lymph node biopsy (preferred over core — preserves architecture); send fresh for cytogenetics/FISH",
        "Core biopsy ± flow cytometry if excisional not feasible",
        "Bone marrow biopsy if lymphoma confirmed or peripheral blood involvement",
      ],
    },
  },

  {
    id: "iron-deficiency",
    label: "Iron Deficiency Anemia",
    specialty: "hematology",
    history: {
      quick: [
        "No melena, hematochezia, or change in stool caliber/frequency",
        "No abdominal pain, dysphagia, or weight loss",
        "Menstrual history: cycle frequency, duration, flooding, clot passage, pads/tampons per day",
        "No pica (ice, dirt, starch) or restless legs",
        "No known celiac disease, IBD, or prior gastric surgery",
        "No NSAIDs, anticoagulants, or regular aspirin use",
        "Prior GI investigations: colonoscopy/gastroscopy — dates and findings",
        "No prior iron deficiency or iron infusions",
        "Dietary history: vegetarian/vegan, restricted eating",
      ],
      full: [
        "Symptoms of anemia: fatigue, exertional dyspnea, palpitations, lightheadedness",
        "Pica (craving ice/pagophagia, dirt, starch) — highly specific for iron deficiency",
        "Restless legs syndrome (associated with iron deficiency independently of anemia)",
        "Dysphagia (Plummer-Vinson syndrome — rare but important)",
        "Dietary history: red meat intake, vegetarian/vegan diet",
        "GI symptoms: melena, bright red rectal bleeding, change in stool caliber/frequency, abdominal pain, weight loss",
        "Menstrual history: cycle frequency, duration, flooding, clot passage, pads/tampons per day",
        "Pregnancy history and current pregnancy status",
        "Prior episodes of IDA and management",
        "Blood donation frequency",
        "Prior GI investigations: colonoscopy, gastroscopy — dates and findings",
        "Medications: NSAIDs, aspirin, anticoagulants, PPIs, antacids",
        "Known conditions: celiac disease, IBD, prior gastric surgery, H. pylori, HHT",
        "Family history of GI malignancy or polyposis",
      ],
    },
    exam: {
      quick: [
        "Pallor: conjunctival, palmar, mucosal",
        "No koilonychia, angular cheilitis, or atrophic glossitis",
        "No tachycardia or flow murmur",
        "No abdominal tenderness, organomegaly, or palpable mass",
        "Rectal exam if GI blood loss suspected",
        "No lymphadenopathy",
      ],
      full: [
        "Pallor: conjunctival, palmar, mucosal",
        "Koilonychia (spoon nails — chronic severe iron deficiency)",
        "Angular cheilitis, atrophic glossitis",
        "Tachycardia, flow murmur (hemodynamic compensation)",
        "Abdomen: tenderness, organomegaly, mass",
        "Rectal exam if GI blood loss suspected (occult blood, mass, hemorrhoids)",
        "Lymphadenopathy (if GI malignancy in DDx)",
      ],
    },
    considerations: [
      "Confirm iron deficiency before treating: ferritin <30 diagnostic; <100 with TSAT <20% consistent in inflammatory states",
      "Ferritin is an acute phase reactant — can be falsely normal/elevated with inflammation, liver disease, malignancy",
      "Pre-menopausal women with clear menorrhagia and no GI symptoms: may treat empirically, reassess if not responding",
      "Men and post-menopausal women: GI source assumed until proven otherwise — colonoscopy ± gastroscopy indicated",
      "Celiac serology in all patients without clear bleeding source (tTG IgA + total IgA)",
      "H. pylori testing if endoscopy performed — treat if positive (improves iron absorption)",
      "IV iron preferred when: oral intolerance, malabsorption, IBD, CKD, post-gastric bypass, need for rapid repletion",
      "Target ferritin >100 with repletion therapy",
      "Thalassemia trait: low MCV, normal/high RBC, normal iron studies — consider hemoglobin electrophoresis",
    ],
    labs: {
      copyable: ["CBC","peripheral blood film","ferritin","serum iron","TIBC","transferrin saturation","reticulocyte count","creatinine","ALT","ALK phos","bili","B12","folate","TSH","tissue transglutaminase IgA","total IgA","H. pylori stool antigen"],
      other: [
        "Colonoscopy ± gastroscopy (mandatory in men and post-menopausal women)",
        "Hemoglobin electrophoresis if thalassemia trait suspected",
        "Small bowel capsule endoscopy if upper and lower GI scopes negative and bleeding continues",
        "CT enterography if small bowel pathology suspected",
      ],
    },
  },

  {
    id: "elevated-ferritin",
    label: "Elevated Ferritin",
    specialty: "hematology",
    history: {
      quick: [
        "No significant alcohol use or known liver disease",
        "No HTN, diabetes, or dyslipidemia (metabolic syndrome/NAFLD)",
        "No history of iron infusion or blood transfusion",
        "No known hemoglobinopathy",
        "No family history of hemochromatosis or iron overload",
        "No known inflammatory disorder or history of malignancy",
        "No fevers, sweats, weight loss, lymphadenopathy, or hematochezia",
      ],
      full: [
        "Degree of elevation: mild (300–1000) vs moderate-marked (1000–10,000) vs extreme (>10,000 → HLH or Still's)",
        "Symptoms of hemochromatosis: fatigue, arthralgias, abdominal pain, loss of libido, skin bronzing",
        "Alcohol intake (quantity, frequency, duration)",
        "Metabolic history: diabetes, obesity, hypertriglyceridemia, hypertension (metabolic syndrome → NAFLD)",
        "Liver disease history: hepatitis B/C, cirrhosis, autoimmune hepatitis",
        "Inflammatory conditions: IBD, rheumatoid arthritis, lupus, adult-onset Still's disease",
        "Recent infection, hospitalization, or inflammatory illness",
        "Malignancy history (ferritin as acute phase reactant)",
        "Transfusion history (secondary iron overload)",
        "Family history of hemochromatosis or liver disease",
        "Iron supplements or multivitamins with iron",
        "If ferritin >10,000: fever, cytopenias, splenomegaly — consider HLH",
      ],
    },
    exam: {
      quick: [
        "No skin bronzing or jaundice",
        "No hepatomegaly, splenomegaly, or stigmata of chronic liver disease",
        "No MCP joint arthropathy (2nd/3rd MCPs — hemochromatosis)",
        "No testicular atrophy",
        "No signs of heart failure",
        "No lymphadenopathy or fever",
      ],
      full: [
        "Skin: bronze discoloration, jaundice",
        "Hepatomegaly, splenomegaly, stigmata of chronic liver disease (spider nevi, palmar erythema, asterixis)",
        "Arthropathy: MCP joint arthritis (2nd and 3rd MCPs classic for hemochromatosis)",
        "Testicular atrophy (hypogonadism in hemochromatosis)",
        "Signs of heart failure (hemochromatosis cardiomyopathy)",
        "Lymphadenopathy, fever — if HLH or malignancy suspected",
      ],
    },
    considerations: [
      "Ferritin is non-specific — always interpret with transferrin saturation (TSAT)",
      "Hereditary hemochromatosis: TSAT >45% + elevated ferritin → HFE gene testing (C282Y, H63D); C282Y homozygote is classic",
      "NAFLD/metabolic syndrome: most common cause of mildly-moderately elevated ferritin; TSAT typically normal",
      "Alcohol: direct hepatocellular damage + acute phase response; AST:ALT >2:1 suggests alcoholic liver disease",
      "Inflammatory: ferritin very high; TSAT low/normal",
      "Malignancy: lymphoma, HCC, leukemia can cause markedly elevated ferritin",
      "HLH triggers: infection (EBV most common), malignancy (lymphoma), autoimmune (Still's, SLE); ferritin often >10,000",
      "MRI liver for iron quantification preferred over biopsy in many cases (T2* sequence)",
      "Phlebotomy in confirmed hemochromatosis — target ferritin <50, TSAT <30%",
    ],
    labs: {
      copyable: ["CBC","peripheral blood film","ferritin","serum iron","TIBC","transferrin saturation","ALT","AST","ALK phos","bili","GGT","albumin","INR","creatinine","glucose","triglycerides","HbA1c","HFE gene testing (C282Y, H63D)","HBsAg","HCV Ab","ANA","anti-smooth muscle Ab","ceruloplasmin"],
      other: [
        "Liver ultrasound (steatosis, cirrhosis, HCC screening)",
        "FibroScan / liver elastography if cirrhosis assessment needed",
        "MRI liver for iron quantification (T2* sequence — preferred over biopsy in many cases)",
        "Liver biopsy if diagnosis uncertain or fibrosis staging needed",
        "If HLH suspected: sCD25, NK cell function, fibrinogen, triglycerides, bone marrow biopsy",
        "Echocardiogram if hemochromatosis with cardiac symptoms",
      ],
    },
  },

  {
    id: "thrombocytopenia",
    label: "Thrombocytopenia",
    specialty: "hematology",
    history: {
      quick: [
        "Duration — acute vs chronic; prior CBC results if available",
        "No petechiae, purpura, mucosal bleeding, menorrhagia, or hematochezia",
        "No recent viral illness, vaccination, or sick contacts",
        "No significant alcohol use, no history of liver disease, prior malignancy, chemotherapy, or radiation; no history of hepatitis B, hepatitis C, or HIV",
        "No known autoimmune disease (SLE, thyroid, antiphospholipid syndrome)",
        "No prior history of thrombocytopenia",
        "No family history of thrombocytopenia, bone marrow failure disorder, leukaemia, etc.",
        "No reports of platelet aggregates on blood film",
      ],
      full: [
        "Duration — acute (<3 months) vs chronic (≥3 months); prior CBC results",
        "Bleeding symptoms: petechiae, purpura, bruising, mucosal bleeding, menorrhagia, GI/GU, CNS",
        "Thrombotic symptoms (HIT, TTP — thrombocytopenia + clots)",
        "Recent infections: viral illness, EBV, CMV, HIV, hepatitis, COVID-19",
        "Recent vaccinations",
        "Medications: heparin (any exposure including flushes), quinine, sulfonamides, vancomycin, GP IIb/IIIa inhibitors, valproic acid, linezolid, chemotherapy",
        "OTC medications, herbals, supplements, alcohol",
        "Autoimmune history (ITP associated with other autoimmune diseases: thyroid, SLE, APS)",
        "Pregnancy status (gestational thrombocytopenia, HELLP, preeclampsia)",
        "Prior platelet count — is this new or long-standing?",
        "Family history of thrombocytopenia or bleeding disorder",
        "Transfusion history (post-transfusion purpura — within 5–10 days of transfusion)",
        "HIV risk factors, liver disease history (hypersplenism)",
      ],
    },
    exam: {
      quick: [
        "Petechiae or purpura present? (distribution, lower legs, feet, oral mucosa)",
        "No oral blood blisters",
        "No splenomegaly, hepatomegaly, or lymphadenopathy",
        "No stigmata of chronic liver disease",
      ],
      full: [
        "Petechiae (non-blanching, gravity-dependent — lower legs, feet, oral mucosa)",
        "Purpura, ecchymoses (distribution, size, pattern)",
        "Oral blood blisters — marker of severe thrombocytopenia",
        "Splenomegaly (hypersplenism, lymphoma, portal hypertension)",
        "Lymphadenopathy (lymphoma, viral infection)",
        "Stigmata of chronic liver disease",
        "Neurologic findings (TTP: confusion, focal deficits — EMERGENCY)",
        "Blood pressure (HUS/TTP overlap), fever (TTP, sepsis, viral)",
      ],
    },
    considerations: [
      "Confirm true thrombocytopenia: check prior CBCs for chronicity; pseudothrombocytopenia (EDTA clumping) — request hematopathologist blood film review",
      "Common outpatient DDx: ITP, drug-induced, viral/post-infectious, alcohol-related, liver disease with hypersplenism, nutritional deficiency (B12, folate)",
      "Secondary causes to exclude: autoimmune disease (SLE, APS), thyroid disease, lymphoma/CLL, MDS, bone marrow infiltration",
      "ITP: most common cause of isolated thrombocytopenia in outpatient — diagnosis of exclusion; normal film morphology, no secondary cause identified",
      "Drug-induced: review all medications, OTCs, supplements; typically resolves 1–2 weeks after stopping offending agent",
      "Inherited thrombocytopenia: consider if longstanding, family history, or large platelets on film",
      "Refer urgently to ED if: schistocytes on film (TMA — possible TTP), severe thrombocytopenia with mucosal bleeding or CNS symptoms",
      "Bone marrow biopsy indications: age >60, additional unexplained cytopenias, abnormal cells on film, ITP refractory to first-line therapy",
    ],
    labs: {
      copyable: ["CBC","reticulocyte count","creatinine","ALT","AST","ALK phos","bili","LDH","haptoglobin","Coombs (DAT)","ANA","TSH","SPEP","free light chains (kappa and lambda)","hematopathologist blood film review"],
      other: [
        "Bone marrow aspirate and trephine biopsy (if indicated — see considerations)",
        "CT abdomen/pelvis if splenomegaly or lymphoma suspected",
        "Ultrasound abdomen if liver disease / portal hypertension suspected",
        "Renal function trend and urinalysis (HUS/TTP)",
        "Pregnancy test if applicable",
      ],
    },
  },

  {
    id: "pancytopenia",
    label: "Pancytopenia",
    specialty: "hematology",
    history: {
      quick: [
        "Duration of symptoms; prior CBC results if available",
        "No fevers, rigors, or recurrent infections (neutropenia)",
        "No mucosal bleeding, petechiae, purpura, or menorrhagia (thrombocytopenia)",
        "No fatigue, exertional dyspnea, or palpitations (anemia)",
        "No medications: chemotherapy, methotrexate, carbamazepine, valproate, phenytoin, chloramphenicol, sulfonamides, antithyroid drugs, gold, linezolid",
        "No significant alcohol use or known liver disease",
        "No recent viral illness (EBV, CMV, HIV, hepatitis, parvovirus B19)",
        "No constitutional symptoms: night sweats, weight loss",
        "No family history of cytopenias or bone marrow failure",
        "No prior radiation or toxic chemical exposures (benzene)",
      ],
      full: [
        "Onset and duration — acute vs subacute vs chronic; prior CBC values if available",
        "Symptoms of anemia: fatigue, exertional dyspnea, palpitations, lightheadedness",
        "Symptoms of thrombocytopenia: petechiae, purpura, mucosal bleeding, menorrhagia, GI bleeding",
        "Symptoms of neutropenia: recurrent or severe infections, prolonged fever, oral ulcers",
        "Constitutional symptoms: fevers, drenching night sweats, weight loss (malignancy/lymphoma)",
        "Medications: chemotherapy, methotrexate, carbamazepine, valproate, phenytoin, chloramphenicol, sulfonamides, antithyroid drugs, gold, linezolid",
        "Alcohol intake (direct marrow toxicity, nutritional deficiencies, hypersplenism)",
        "Recent viral illness: EBV, CMV, HIV, hepatitis (A/B/C), parvovirus B19 (aplastic crisis)",
        "Prior radiation therapy or toxic exposures (benzene, other solvents)",
        "B12/folate deficiency risk: diet, prior gastric surgery, malabsorption, metformin, methotrexate",
        "Autoimmune conditions: SLE, rheumatoid arthritis",
        "Family history of bone marrow failure, cytopenias, or early hematologic malignancy",
        "History of prior malignancy (marrow infiltration, post-chemotherapy)",
      ],
    },
    exam: {
      quick: [
        "Pallor: conjunctival, palmar, mucosal",
        "Petechiae, purpura, or ecchymoses — document distribution",
        "No oral ulcers or signs of active infection",
        "No lymphadenopathy",
        "No splenomegaly or hepatomegaly",
        "No stigmata of chronic liver disease",
        "No dysmorphic features if young patient (Fanconi anemia: short stature, café-au-lait spots, thumb anomalies)",
      ],
      full: [
        "Pallor: conjunctival, palmar, mucosal",
        "Petechiae (gravity-dependent — lower legs), purpura, ecchymoses",
        "Oral ulcers, pharyngitis, signs of infection (neutropenia complications)",
        "Lymphadenopathy (lymphoma, viral infection, leukemia)",
        "Splenomegaly (lymphoma, CLL, hypersplenism, storage disease, portal hypertension)",
        "Hepatomegaly (infiltration, hepatitis, lymphoma)",
        "Stigmata of chronic liver disease (portal hypertension → hypersplenism)",
        "Dysmorphic features: short stature, café-au-lait spots, thumb anomalies (Fanconi anemia — if young patient)",
        "Skin: vitiligo (autoimmune association), telangiectasias",
      ],
    },
    considerations: [
      "Organize DDx: decreased production (aplastic anemia, MDS, leukemia/marrow infiltration, B12/folate deficiency, drug/toxin, viral) vs peripheral destruction/sequestration (hypersplenism, autoimmune, TMA/DIC)",
      "Peripheral blood film FIRST — look for blasts (leukemia), hypersegmented neutrophils (B12/folate), dysplastic cells (MDS), schistocytes (TMA)",
      "B12 and folate deficiency: easily missed — can cause severe pancytopenia with megaloblastic anemia and hypersegmented neutrophils on film",
      "Aplastic anemia: hypocellular marrow + pancytopenia — URGENT hematology referral; severe AA (ANC <0.5, platelets <20, reticulocytes <1%) requires early BMT evaluation or ATG/cyclosporine",
      "MDS: typically older adults; dysplastic cells on film; bone marrow with cytogenetics essential for diagnosis and prognosis",
      "Acute leukemia: new pancytopenia with blasts on film or rapidly falling counts — URGENT same-day hematology",
      "Bone marrow biopsy almost always required unless a reversible cause (B12, drug, viral) is clearly identified and responsive to treatment",
      "Drug-induced aplasia: stop offending agent; recovery typically 1–3 weeks unless aplasia is established",
      "Paroxysmal nocturnal hemoglobinuria (PNH): associated with aplastic anemia — send flow cytometry for GPI-anchored proteins on all aplastic presentations",
    ],
    labs: {
      copyable: ["CBC","peripheral blood film","reticulocyte count","B12","folate","ferritin","serum iron","TIBC","TSH","creatinine","ALT","AST","ALK phos","bili","albumin","INR","LDH","haptoglobin","Coombs (DAT)","ANA","anti-dsDNA","HIV 4th gen Ag/Ab","HBsAg","HBcAb","HCV Ab","EBV VCA IgM/IgG","CMV IgM/IgG","parvovirus B19 IgM/IgG","SPEP","flow cytometry peripheral blood (PNH clone — GPI-anchored proteins)"],
      other: [
        "Bone marrow aspirate and trephine biopsy with cytogenetics and FISH (almost always required)",
        "CT chest/abdomen/pelvis if lymphoma or infiltrative malignancy suspected",
        "Chromosomal breakage studies (diepoxybutane / DEB test) if Fanconi anemia suspected (young patient, dysmorphic features)",
        "Abdominal ultrasound if splenomegaly or liver disease suspected",
      ],
    },
  },

  {
    id: "leukocytosis-nyd",
    label: "Leukocytosis NYD",
    specialty: "hematology",
    history: {
      quick: [
        "Duration — acute vs chronic; prior CBC results if available",
        "No fever, chills, or localizing symptoms of infection",
        "No medications: corticosteroids, G-CSF, lithium, beta-agonists",
        "No smoking history (causes chronic neutrophilia up to ~25×10⁹/L)",
        "No known inflammatory or autoimmune condition",
        "No constitutional symptoms: night sweats, weight loss",
        "No symptoms of splenomegaly: early satiety, LUQ fullness",
        "No prior malignancy or family history of blood disorder",
      ],
      full: [
        "Duration and trend — acute (stress, infection) vs persistent/progressive (primary hematologic process)",
        "Prior CBC values — is this new, or longstanding and stable?",
        "Infectious symptoms: fever, rigors, localizing symptoms (cough, dysuria, cellulitis, dental abscess)",
        "Inflammatory conditions: IBD, rheumatoid arthritis, vasculitis, gout flare",
        "Medications: corticosteroids (demargination), G-CSF, lithium, beta-2 agonists, all-trans retinoic acid (ATRA)",
        "Smoking history (causes chronic neutrophilia — up to ~25×10⁹/L; monocytosis)",
        "Physical or emotional stress (catecholamine-mediated demargination)",
        "Asplenia or functional hyposplenia: post-splenectomy, sickle cell disease",
        "Constitutional symptoms: night sweats, weight loss, fevers (lymphoma, leukemia, MPN)",
        "Symptoms of hyperviscosity (CML with very high WBC): headache, blurred vision, priapism",
        "Family history of blood disorders or malignancy",
        "Prior malignancy (marrow infiltration, paraneoplastic leukocytosis)",
      ],
    },
    exam: {
      quick: [
        "No fever or signs of active infection",
        "No lymphadenopathy",
        "No splenomegaly or hepatomegaly",
        "No sternal tenderness (leukemia/MPN with marrow expansion)",
        "No skin infiltration or gingival hypertrophy (AML monocytic subtype)",
      ],
      full: [
        "Temperature and signs of infection (source-directed examination)",
        "Lymphadenopathy: cervical, axillary, inguinal (CLL, lymphoma)",
        "Splenomegaly — massive splenomegaly strongly suggests CML or MPN",
        "Hepatomegaly",
        "Sternal tenderness (marrow expansion in leukemia or MPN)",
        "Skin: leukemia cutis (violaceous nodules), gingival hypertrophy (AML monocytic — M4/M5)",
        "Signs of leukostasis if WBC >100×10⁹/L: altered mental status, hypoxia, retinal venous distension",
        "Pallor, petechiae (if accompanied by cytopenias — suggests leukemia, not reactive leukocytosis)",
      ],
    },
    considerations: [
      "First step: review the peripheral blood film and differential — the WBC type drives the entire workup",
      "Neutrophilia: reactive (infection, steroids, stress, smoking, asplenia) vs CML (left shift to blasts + basophilia + eosinophilia); BCR-ABL PCR is essential if CML suspected",
      "Lymphocytosis: reactive (EBV, CMV, pertussis) vs CLL (CD5+/CD23+ B-cells on flow); CLL = absolute lymphocytosis >5×10⁹/L with CLL immunophenotype on two occasions",
      "Monocytosis (>1×10⁹/L): CMML, AML monocytic differentiation, reactive (TB, sarcoid, IBD, recovering marrow after chemotherapy)",
      "Eosinophilia (>0.5×10⁹/L): parasites (Strongyloides, Toxocara), drug hypersensitivity, atopy, EGPA; if >1.5×10⁹/L — evaluate for end-organ damage (cardiac, pulmonary)",
      "Blasts on film: URGENT — assume acute leukemia until proven otherwise; hematology same day",
      "CML: typically marked leukocytosis (often 50–400×10⁹/L) with full myeloid left shift, basophilia, eosinophilia, splenomegaly — BCR-ABL PCR confirms; treat with TKI",
      "Pure reactive leukocytosis: WBC rarely >30×10⁹/L — higher counts without a clear trigger warrant hematologic workup",
      "Leukostasis emergency: WBC >100×10⁹/L with symptoms (hypoxia, confusion, priapism) — urgent leukapheresis",
    ],
    labs: {
      copyable: ["CBC with differential","peripheral blood film","reticulocyte count","creatinine","ALT","ALK phos","bili","LDH","uric acid","B12 (elevated in CML/MPN)","ESR","CRP","ferritin","BCR-ABL quantitative PCR","JAK2 V617F mutation","flow cytometry peripheral blood","EBV VCA IgM/IgG","CMV IgM/IgG","HIV 4th gen Ag/Ab","TSH"],
      other: [
        "CT chest/abdomen/pelvis if lymphadenopathy or organomegaly on exam",
        "Bone marrow aspirate and trephine biopsy with cytogenetics (if primary hematologic process suspected)",
        "Echocardiogram if eosinophilia >1.5×10⁹/L (hypereosinophilic syndrome — screen for cardiac involvement)",
        "Stool O&P and serology if eosinophilia with travel history or parasitic exposure",
        "FISH for BCR-ABL t(9;22) if CML suspected and PCR result pending",
      ],
    },
  },

  {
    id: "hypercoagulable",
    label: "Hypercoagulable State / DVT Workup",
    specialty: "hematology",
    history: {
      quick: [
        "Provoked vs unprovoked: recent surgery, trauma, immobility, hospitalization, active malignancy, pregnancy/postpartum, OCP/HRT",
        "Location of thrombosis: proximal DVT, PE, or unusual site (cerebral, splanchnic, upper extremity)",
        "Prior VTE: number of events, sites, provoked or unprovoked",
        "No family history of VTE (first-degree relative, age <50 at event)",
        "No recurrent pregnancy loss (≥3 first-trimester or ≥1 late loss — antiphospholipid syndrome)",
        "No symptoms of occult malignancy",
        "No autoimmune symptoms (SLE — associated with antiphospholipid syndrome)",
      ],
      full: [
        "Nature of current event: DVT (proximal vs distal), PE, or unusual-site thrombosis (cerebral sinus, portal/mesenteric/splenic/hepatic vein, upper extremity)",
        "Provoked vs unprovoked: surgery (<12 wks), trauma, hospitalization, prolonged immobility, active malignancy, pregnancy or postpartum, OCP/HRT/testosterone",
        "Prior VTE: dates, sites, provoked or unprovoked, anticoagulation duration and adherence, recurrence on treatment",
        "Family history of VTE — first-degree relative, age at event, site, known thrombophilia",
        "Obstetric history: recurrent pregnancy loss (≥3 consecutive first-trimester losses or ≥1 fetal loss after 10 weeks)",
        "Autoimmune symptoms: malar rash, oral ulcers, arthritis (SLE — associated with APS)",
        "Malignancy history or symptoms: weight loss, hemoptysis, GI bleeding, hematuria",
        "Medications: OCP, HRT, testosterone, tamoxifen, thalidomide, lenalidomide, bevacizumab",
        "Prior heparin exposure and timing (HIT if thrombocytopenia present)",
        "Smoking history (additional VTE risk factor)",
        "Long-distance travel",
      ],
    },
    exam: {
      quick: [
        "DVT limb: unilateral swelling, erythema, warmth, calf tenderness",
        "Signs of PE: tachycardia, tachypnea, hypoxia, pleuritic chest pain",
        "No lymphadenopathy, abdominal mass, or organomegaly (malignancy)",
        "No malar rash or oral ulcers (SLE/APS)",
        "Skin: livedo reticularis or superficial thrombophlebitis (antiphospholipid syndrome)",
      ],
      full: [
        "DVT limb: unilateral swelling (measure bilateral calf circumference), erythema, warmth, tenderness along deep venous course, pitting edema",
        "Signs of PE: tachycardia, tachypnea, hypoxia (SpO2 on room air), pleuritic chest pain, decreased breath sounds, right heart strain signs",
        "Lymphadenopathy (malignancy)",
        "Abdominal exam: organomegaly, masses (malignancy; splanchnic thrombosis from MPN)",
        "Skin: livedo reticularis, livedo racemosa, superficial thrombophlebitis, skin necrosis (antiphospholipid syndrome)",
        "Malar rash, oral ulcers (SLE)",
        "Neurologic: focal deficits (cerebral sinus thrombosis or paradoxical embolism)",
      ],
    },
    considerations: [
      "Provoked vs unprovoked is the most important initial distinction — it determines anticoagulation duration and the yield of thrombophilia testing",
      "Thrombophilia testing indications: unprovoked VTE (especially age <50), unusual site, recurrent events, strong family history, recurrent pregnancy loss (APS workup)",
      "Do NOT test during the acute event or while on anticoagulation — most functional assays are affected; defer ≥3 months after stopping anticoagulation",
      "Exception: antiphospholipid Ab can be sent during the acute event (informs treatment choice — warfarin preferred over DOAC in APS); confirm positive result ≥12 weeks later",
      "Antiphospholipid syndrome (APS): requires positive Ab on 2 occasions ≥12 weeks apart plus clinical event; triple-positive (LA + aCL + anti-β2GP1) = highest recurrence risk",
      "JAK2 V617F: order for unusual-site thrombosis (splanchnic, cerebral sinus) — MPNs are a leading cause and are treatable",
      "Hereditary thrombophilias: Factor V Leiden and prothrombin G20210A are PCR-based (not affected by anticoagulation — can test anytime)",
      "Protein C, Protein S, Antithrombin: functional assays affected by acute thrombosis, warfarin (C/S), heparin (AT), liver disease; test on DOAC or defer",
      "Malignancy screening for unprovoked VTE: CT chest/abdomen/pelvis is reasonable if not performed recently — do not over-investigate",
      "Consider indefinite anticoagulation for unprovoked proximal DVT/PE with low bleeding risk — discuss risk-benefit explicitly",
    ],
    labs: {
      copyable: ["CBC","peripheral blood film","creatinine","ALT","ALK phos","bili","INR","PTT","antiphospholipid Ab panel (lupus anticoagulant, anticardiolipin IgG/IgM, anti-beta2-GP1 IgG/IgM)","Factor V Leiden mutation (PCR)","Prothrombin G20210A mutation (PCR)","Protein C activity","Protein S activity (free antigen)","Antithrombin activity","homocysteine","JAK2 V617F mutation","SPEP","LDH","uric acid","ESR","CRP","urinalysis"],
      other: [
        "Doppler ultrasound lower limbs (DVT confirmation and extent)",
        "CT pulmonary angiography (PE diagnosis) or V/Q scan if contrast contraindicated",
        "CT abdomen/pelvis with IV contrast (malignancy screening for unprovoked VTE; splanchnic vein thrombosis assessment)",
        "Echocardiogram (right heart strain, intracardiac thrombus, PFO if paradoxical embolism suspected)",
        "MRI/MRV brain if cerebral sinus thrombosis suspected",
        "CT or MR venography for splanchnic vein thrombosis (portal, mesenteric, splenic, hepatic veins)",
        "Age-appropriate cancer screening review (mammography, colonoscopy, PSA) if not up to date",
      ],
    },
  },

  {
    id: "splenomegaly-nyd",
    label: "Splenomegaly NYD",
    specialty: "hematology",
    history: {
      quick: [
        "Early satiety, LUQ discomfort/fullness, or left shoulder tip pain",
        "No fevers, night sweats, or weight loss",
        "No pruritus after hot shower",
        "No symptoms of portal hypertension: hematemesis, melena, jaundice, ascites",
        "No significant alcohol use or known liver disease",
        "No thrombotic events (DVT, portal/splenic vein thrombosis, Budd-Chiari)",
        "No travel to malaria or schistosomiasis-endemic region",
        "No known hemolytic anemia, hemoglobinopathy, or storage disorder",
        "No prior malignancy or family history of blood disorder",
      ],
      full: [
        "Symptoms attributable to splenomegaly: early satiety, LUQ discomfort/fullness, left shoulder tip pain",
        "Constitutional symptoms: fevers, night sweats, weight loss (lymphoma, infection, malignancy)",
        "Symptoms of cytopenias from hypersplenism: bleeding, fatigue, recurrent infections",
        "Thrombotic events (MPNs — Budd-Chiari, portal/splenic vein thrombosis)",
        "Pruritus after hot shower (polycythemia vera)",
        "Symptoms of portal hypertension: hematemesis, melena, jaundice, ascites",
        "Alcohol use history (liver disease, portal hypertension)",
        "Travel history: malaria, leishmaniasis, schistosomiasis (if endemic region)",
        "Sick contacts, infectious exposures (EBV, CMV)",
        "Family history of splenomegaly, hemolytic anemia, or liver disease",
        "Known conditions: sickle cell disease, hereditary spherocytosis, thalassemia, storage disorders",
        "Prior malignancy (lymphoma — most common hematologic cause)",
        "Medications: G-CSF, immunosuppressants",
      ],
    },
    exam: {
      quick: [
        "Spleen size: document span on percussion and cm below costal margin",
        "Massive splenomegaly (>20 cm) — narrows DDx significantly",
        "No hepatomegaly or stigmata of chronic liver disease",
        "No lymphadenopathy",
        "No jaundice or pallor",
        "No plethora (polycythemia vera)",
        "No bone tenderness",
        "No ascites",
      ],
      full: [
        "Quantify splenomegaly: span on percussion (Traube's space) and cm below costal margin",
        "Massive splenomegaly (>20 cm): think myelofibrosis, CML, hairy cell leukemia, Gaucher disease, malaria",
        "Hepatomegaly (portal hypertension, infiltrative liver disease, lymphoma, storage disease)",
        "Stigmata of chronic liver disease: spider nevi, caput medusae, gynecomastia, palmar erythema, asterixis",
        "Lymphadenopathy (lymphoma, CLL, infectious)",
        "Jaundice (hemolytic anemia, liver disease)",
        "Skin: pallor (hemolysis), plethora (polycythemia vera), purpura",
        "Bone tenderness (myeloproliferative neoplasm, malignancy)",
        "Ascites (portal hypertension)",
      ],
    },
    considerations: [
      "Organize DDx by mechanism: congestive (portal HTN, hepatic vein obstruction), infiltrative (lymphoma, leukemia, storage disease, EMH), infectious/inflammatory, hemolytic, vascular",
      "Most common causes in practice: portal hypertension (cirrhosis), hematologic malignancy (lymphoma, CLL, MPN), infectious (EBV, CMV), hemolytic anemia",
      "MPNs: JAK2 V617F essential (positive in ~95% PV, ~55% ET/MF); CALR and MPL if JAK2 negative",
      "CML: typically massive splenomegaly + leukocytosis with left shift — BCR-ABL by PCR",
      "Hairy cell leukemia: splenomegaly + monocytopenia + cytopenias; BRAF V600E; flow cytometry diagnostic",
      "Gaucher disease (beta-glucocerebrosidase deficiency): most common storage disorder — enzyme assay; consider in young patients with massive splenomegaly",
      "Bone marrow biopsy: essential if MPN, lymphoma, leukemia, or infiltrative marrow process suspected",
      "Splenic vein thrombosis can cause isolated splenomegaly without portal hypertension — Doppler US or CT venography",
      "Vaccination required pre-splenectomy if heading that direction (pneumococcus, meningococcus, Hib)",
    ],
    labs: {
      copyable: ["CBC","peripheral blood film","reticulocyte count","Coombs (DAT)","LDH","haptoglobin","bili (total and direct)","creatinine","ALT","AST","ALK phos","GGT","albumin","INR","ferritin","B12","uric acid","JAK2 V617F mutation","CALR mutation","MPL mutation","BCR-ABL quantitative PCR","EBV VCA IgM/IgG","CMV IgM/IgG","HBsAg","HCV Ab","HIV 4th gen Ag/Ab","beta-glucocerebrosidase enzyme assay","flow cytometry peripheral blood","ESR","CRP"],
      other: [
        "Ultrasound abdomen with Doppler (spleen size, liver texture, portal/splenic vein patency, ascites)",
        "CT abdomen/pelvis with IV contrast (lymphadenopathy, vascular anatomy)",
        "PET-CT if lymphoma suspected",
        "Bone marrow aspirate and trephine biopsy with cytogenetics and flow cytometry",
        "Liver biopsy if infiltrative liver disease and diagnosis unclear after non-invasive workup",
        "Upper GI endoscopy if portal hypertension confirmed (varices screening)",
        "Malaria thick/thin film + rapid antigen if travel to endemic area",
      ],
    },
  },

  // ─────────────────────────────────────────────
  // ONCOLOGY
  // ─────────────────────────────────────────────

  {
    id: "metastatic-nyd",
    label: "New Metastatic Cancer NYD",
    specialty: "oncology",
    history: {
      quick: [
        "Presenting site(s) and timeline of symptoms",
        "No prior malignancy; prior screening history (PSA, mammogram, Pap, colonoscopy, lung CT) — dates and results",
        "Organ-specific symptoms: cough/hemoptysis, change in bowel habit, breast lump, hematuria, dysphagia, jaundice, postmenopausal bleeding",
        "Constitutional symptoms: weight loss (amount and duration), anorexia, fatigue, fevers",
        "Smoking history (pack-years); alcohol use history",
        "Family history: cancer type, age of onset, degree of relatedness",
        "Occupational exposures (asbestos, benzene)",
        "ECOG performance status — document explicitly",
        "Comorbidities relevant to treatment (cardiac, renal, hepatic, neuropathy)",
        "Goals of care — patient's understanding of situation",
      ],
      full: [
        "Presenting symptoms and timeline — which site(s) prompted investigation",
        "Constitutional symptoms: weight loss (how much, over what time), anorexia, fatigue, fevers",
        "Organ-specific symptoms: cough/hemoptysis (lung), change in bowel habit/rectal bleeding (CRC), breast lump (breast), hematuria/flank pain (renal/bladder/prostate), dysphagia (esophagus/stomach), jaundice/RUQ pain (hepatobiliary/pancreas), postmenopausal bleeding (gynecologic)",
        "Smoking history (pack-years) — lung adenocarcinoma, SCC, urothelial",
        "Alcohol use — HCC, esophageal, head and neck",
        "Occupational exposures: asbestos (mesothelioma, lung), benzene, vinyl chloride",
        "Family history: which cancers, age of onset, degree of relatedness (BRCA, Lynch, APC)",
        "Personal history of prior malignancy",
        "Prior cancer screening: PSA, mammogram, Pap, colonoscopy, lung CT — dates and results",
        "Sun exposure, skin lesions, prior skin biopsies (melanoma)",
        "ECOG performance status — document explicitly",
        "Comorbidities relevant to treatment: cardiac, renal, hepatic, neuropathy",
        "Goals of care — has this been initiated? Patient's understanding of situation?",
      ],
    },
    exam: {
      quick: [
        "ECOG performance status (0–4): document explicitly",
        "Cachexia or muscle wasting",
        "Lymphadenopathy: cervical, supraclavicular (Virchow's), axillary, inguinal",
        "Breast exam bilateral including axillary nodes — women AND men",
        "Chest: effusion, decreased breath sounds",
        "Abdomen: hepatomegaly (nodular), ascites, masses; rectal exam",
        "Skin: pigmented lesions, jaundice, nodules",
        "Neurologic: focal deficits, papilledema, cord compression signs",
        "Bone tenderness on palpation (vertebral, long bones)",
      ],
      full: [
        "ECOG performance status (0–4): document explicitly",
        "Cachexia, muscle wasting, nutritional status",
        "Lymphadenopathy: cervical, supraclavicular (Virchow's — left), axillary, inguinal",
        "Breast exam (bilateral, including axillary nodes) — in women AND men",
        "Chest: decreased breath sounds (effusion), dullness, wheezing",
        "Abdomen: hepatomegaly (nodular = metastases), ascites, masses",
        "Rectal exam: prostate (size, asymmetry, nodules), rectal mass",
        "Skin: pigmented lesions, nodules, jaundice",
        "Neurologic: focal deficits, raised ICP signs (papilledema), cord compression signs",
        "Bone tenderness on palpation (vertebral, long bones)",
      ],
    },
    considerations: [
      "Tissue biopsy mandatory before treatment — identify primary, molecular profile, and histology",
      "Biopsy most accessible lesion (prefer metastatic site — confirms metastatic disease and provides tissue)",
      "Request: H&E, IHC panel directed at likely primary, molecular/NGS panel (EGFR, ALK, ROS1, PD-L1 for lung; MSI/MMR, KRAS, NRAS, BRAF for CRC; HER2; broad NGS if available)",
      "Cancer of unknown primary (CUP) ~3–5% of all cancers — favorable subsets: midline germ cell, peritoneal carcinomatosis in women, neuroendocrine",
      "Urgency assessment: spinal cord compression (dexamethasone NOW + urgent MRI spine), SVC syndrome, hypercalcemia, pericardial effusion, symptomatic CNS mets",
      "Multidisciplinary tumor board discussion before treatment decisions",
      "Palliative care referral early — associated with better QoL and sometimes survival",
      "Hereditary cancer evaluation: young onset, multiple primaries, family history, specific histologies (MMR-deficient CRC → Lynch)",
    ],
    labs: {
      copyable: ["CBC","peripheral blood film","creatinine","electrolytes","calcium","albumin","ALT","AST","ALK phos","bili","LDH","INR","PTT","PSA","AFP","CEA","CA 19-9","CA-125","beta-HCG","SPEP","urine protein electrophoresis","TSH","cortisol (AM)","urinalysis"],
      other: [
        "CT chest/abdomen/pelvis with IV contrast (staging — almost always first step)",
        "CT neck if head/neck primary suspected or cervical adenopathy",
        "PET-CT: unknown primary localization, lymphoma staging, selected solid tumors",
        "MRI brain with gadolinium if neurologic symptoms or high CNS tropism primary (lung, breast, melanoma, renal, CRC)",
        "MRI whole spine URGENT if cord compression suspected",
        "Bone scan if bone pain or elevated ALP (consider PSMA PET if prostate cancer suspected)",
        "Biopsy most accessible lesion: H&E + IHC panel + molecular/NGS; send fresh/frozen for biobanking",
        "Echocardiogram if baseline needed prior to cardiotoxic therapy",
        "PFTs if thoracic surgery or bleomycin-containing regimen planned",
      ],
    },
  },

];
